# Generated by Django 6.0.3 on 2026-03-20 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Bodega')),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='N° de Lote')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('hu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Handling Unit (HU)')),
                ('hu_padre', models.CharField(blank=True, max_length=50, null=True, verbose_name='HU Padre')),
                ('m3', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Volumen (M3)')),
                ('dias_estado', models.IntegerField(default=0, verbose_name='Días Estado')),
                ('fecha_fabricacion', models.DateField(blank=True, help_text='Clave para lógica FIFO (First In First Out).', null=True, verbose_name='Fecha de Fabricación')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Clave para lógica FEFO (First Expired First Out).', null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Ingreso al Sistema')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_vencimiento', 'fecha_fabricacion'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Ubicación')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('BLOQUEADA', 'Bloqueada')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['zona', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Recepción)'), ('SALIDA', 'Salida (Picking/Despacho)'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Positivo para entradas, negativo para salidas.')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referencia (N° Pedido, Guía, etc.)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True)),
                ('ean13', models.CharField(blank=True, max_length=50, verbose_name='EAN 13')),
                ('uom', models.CharField(default='CAJA', max_length=30, verbose_name='Unidad de Medida (UoM)')),
                ('requiere_control_vencimiento', models.BooleanField(default=True, help_text='Si activo, el sistema obliga a pickear el lote con fecha de vencimiento más próxima.', verbose_name='¿Requiere control de vencimiento? (FEFO)')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(help_text='Empresa dueña de este SKU. El cliente solo verá sus propios productos.', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='usuarios.empresa', verbose_name='Empresa Propietaria')),
            ],
            options={
                'verbose_name': 'Producto / SKU',
                'verbose_name_plural': 'Productos / SKUs',
                'ordering': ['empresa', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.ubicacion'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Zona')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='inventario.bodega')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['bodega', 'nombre'],
                'unique_together': {('bodega', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventario.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('zona', 'codigo')},
        ),
    ]
