# Generated by Django 6.0.3 on 2026-03-20 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rut', models.CharField(blank=True, help_text='Formato: 12.345.678-9', max_length=12, unique=True, verbose_name='RUT')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Fantasía')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre de Contacto')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Empresa Activa?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa Cliente',
                'verbose_name_plural': 'Empresas Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador WMS'), ('CLIENTE', 'Cliente B2B')], default='CLIENTE', max_length=20, verbose_name='Rol en el sistema')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('empresa', models.ForeignKey(blank=True, help_text='Obligatorio para rol CLIENTE. Dejar vacío para ADMIN u OPERADOR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.empresa', verbose_name='Empresa Asociada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='PuntoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Punto de Entrega')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('es_centro_distribucion', models.BooleanField(default=False, help_text='Marcar si este punto es un CD que recibe mercancía y redistribuye (crossdocking).', verbose_name='¿Es Centro de Distribución?')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_entrega', to='usuarios.empresa', verbose_name='Empresa Propietaria')),
            ],
            options={
                'verbose_name': 'Punto de Entrega',
                'verbose_name_plural': 'Puntos de Entrega',
                'ordering': ['empresa', 'nombre'],
            },
        ),
    ]
