# Generated by Django 6.0.3 on 2026-03-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador WMS'), ('BODEGA', 'Personal de Bodega / Picking'), ('CLIENTE', 'Cliente B2B')], default='CLIENTE', max_length=20, verbose_name='Rol en el sistema'),
        ),
    ]
