# Generated by Django 6.0.3 on 2026-03-17 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE_BACKLOG', 'Pendiente en Backlog'), ('AUTORIZADA', 'Autorizada'), ('EN_PICKING', 'En Proceso de Picking'), ('DESPACHADA', 'Despachada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_BACKLOG', max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_requerida', models.DateField(verbose_name='Fecha en que se necesita el despacho')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_picking', models.DateTimeField(blank=True, null=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('referencia_cliente', models.CharField(blank=True, max_length=100, verbose_name='N° de Orden / Referencia del Cliente')),
                ('observaciones', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente B2B')),
                ('despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_despachadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud B2B',
                'verbose_name_plural': 'Solicitudes B2B',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_despachada', models.PositiveIntegerField(default=0)),
                ('lote_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitud', to='inventario.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Item de Solicitud',
                'verbose_name_plural': 'Items de Solicitud',
            },
        ),
    ]
